# Generated by Django 6.0 on 2026-02-13 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='verified_status',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='donation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='urgency',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospitalprofile'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
